name = "golf-platform"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "golf-db"
database_id = "81aeb8b9-1757-4f95-b74a-50bf55486220"
